/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CapacityAnalysisResponseForecastCapacityAlerts struct {

	AlertType string `json:"alert_type,omitempty"`

	Threshold string `json:"threshold,omitempty"`

	EstimatedDate time.Time `json:"estimated_date,omitempty"`

	DaysRemaining int32 `json:"days_remaining,omitempty"`

	Severity string `json:"severity,omitempty"`
}
