/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Incident struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Description string `json:"description,omitempty"`

	Severity string `json:"severity"`

	Status string `json:"status"`

	AffectedResources []string `json:"affected_resources,omitempty"`

	Assignee string `json:"assignee,omitempty"`

	AcknowledgedBy string `json:"acknowledged_by,omitempty"`

	AcknowledgedAt time.Time `json:"acknowledged_at,omitempty"`

	ResolvedBy string `json:"resolved_by,omitempty"`

	ResolvedAt time.Time `json:"resolved_at,omitempty"`

	Resolution string `json:"resolution,omitempty"`

	RootCause string `json:"root_cause,omitempty"`

	Comments []IncidentComments `json:"comments,omitempty"`

	Tags []string `json:"tags,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
