/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Script struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Category string `json:"category"`

	Language string `json:"language"`
	// 腳本內容
	Content string `json:"content,omitempty"`

	Parameters []ScriptParameters `json:"parameters,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Version string `json:"version,omitempty"`

	CreatedBy string `json:"created_by,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
