/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CapacityAnalysisResponseRecommendations struct {

	Type_ string `json:"type,omitempty"`

	Resource string `json:"resource,omitempty"`

	Priority string `json:"priority,omitempty"`

	CurrentAllocation float64 `json:"current_allocation,omitempty"`

	RecommendedAllocation float64 `json:"recommended_allocation,omitempty"`

	Reasoning string `json:"reasoning,omitempty"`

	CostImpact *CapacityAnalysisResponseCostImpact `json:"cost_impact,omitempty"`
}
