/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {
	// 錯誤代碼
	Error_ string `json:"error"`
	// 錯誤訊息
	Message string `json:"message"`
	// 錯誤詳情
	Details *interface{} `json:"details,omitempty"`
	// 請求追蹤 ID
	RequestId string `json:"request_id,omitempty"`
}
