/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkScanRequest struct {
	// CIDR 格式的網段（如 192.168.1.0/24）
	Cidr string `json:"cidr"`

	PortRanges []string `json:"port_ranges,omitempty"`
	// 掃描超時時間（秒）
	Timeout int32 `json:"timeout,omitempty"`
}
