/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2001Alerts struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Severity string `json:"severity,omitempty"`

	Status string `json:"status,omitempty"`

	ResourceName string `json:"resource_name,omitempty"`

	Message string `json:"message,omitempty"`

	FiredAt time.Time `json:"fired_at,omitempty"`

	ResolvedAt time.Time `json:"resolved_at,omitempty"`
}
