/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type DiagnosticHistoryListItems struct {

	SessionId string `json:"session_id,omitempty"`

	IncidentId string `json:"incident_id,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	CompletedAt time.Time `json:"completed_at,omitempty"`

	Summary string `json:"summary,omitempty"`
}
