/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserCreateRequest struct {

	Username string `json:"username"`

	Email string `json:"email"`

	Password string `json:"password"`

	Name string `json:"name,omitempty"`

	Role string `json:"role"`

	TeamIds []string `json:"team_ids,omitempty"`

	Department string `json:"department,omitempty"`

	Phone string `json:"phone,omitempty"`
}
