/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CapacityAnalysisResponseCurrentUsage struct {

	Average float64 `json:"average,omitempty"`

	Peak float64 `json:"peak,omitempty"`

	Percentile95 float64 `json:"percentile_95,omitempty"`
}
