/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CapacityAnalysisResponseForecast struct {

	Trend string `json:"trend,omitempty"`
	// 預測多少天後達到容量上限
	DaysToCapacity int32 `json:"days_to_capacity,omitempty"`
	// 月增長率百分比
	GrowthRate float64 `json:"growth_rate,omitempty"`

	CapacityAlerts []CapacityAnalysisResponseForecastCapacityAlerts `json:"capacity_alerts,omitempty"`
}
