/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfileUpdateRequest struct {

	Name string `json:"name,omitempty"`

	Phone string `json:"phone,omitempty"`

	LineToken string `json:"line_token,omitempty"`

	Department string `json:"department,omitempty"`

	AvatarUrl string `json:"avatar_url,omitempty"`
}
