/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Schedule struct {

	Id string `json:"id,omitempty"`

	ScriptId string `json:"script_id,omitempty"`

	CronExpression string `json:"cron_expression,omitempty"`

	Enabled bool `json:"enabled,omitempty"`

	Parameters *interface{} `json:"parameters,omitempty"`

	TargetResources []string `json:"target_resources,omitempty"`

	NextRun time.Time `json:"next_run,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
