/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AlertRule struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Condition *AlertRuleCondition `json:"condition"`

	Severity string `json:"severity,omitempty"`

	Enabled bool `json:"enabled"`

	NotificationChannels []string `json:"notification_channels,omitempty"`

	ResourceFilter *AlertRuleResourceFilter `json:"resource_filter,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
