/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResourceDistributionByGroup struct {

	GroupId string `json:"group_id,omitempty"`

	GroupName string `json:"group_name,omitempty"`

	Total int32 `json:"total,omitempty"`

	Healthy int32 `json:"healthy,omitempty"`

	Warning int32 `json:"warning,omitempty"`

	Critical int32 `json:"critical,omitempty"`
}
