/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Resource struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Type_ string `json:"type"`

	Status string `json:"status"`

	IpAddress string `json:"ip_address,omitempty"`

	Location string `json:"location,omitempty"`

	GroupId string `json:"group_id,omitempty"`

	GroupName string `json:"group_name,omitempty"`

	Tags []string `json:"tags,omitempty"`
	// 負責人
	Owner string `json:"owner,omitempty"`

	Description string `json:"description,omitempty"`

	MaintenanceWindow *MaintenanceWindow `json:"maintenance_window,omitempty"`

	Metrics *ResourceMetrics `json:"metrics,omitempty"`

	Metadata ModelMap `json:"metadata,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
