/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AuditLog struct {

	Id string `json:"id,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	UserId string `json:"user_id,omitempty"`

	Username string `json:"username,omitempty"`

	Action string `json:"action,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`

	ResourceId string `json:"resource_id,omitempty"`

	ResourceName string `json:"resource_name,omitempty"`

	Changes *AuditLogChanges `json:"changes,omitempty"`

	Result string `json:"result,omitempty"`

	ErrorMessage string `json:"error_message,omitempty"`

	IpAddress string `json:"ip_address,omitempty"`

	UserAgent string `json:"user_agent,omitempty"`
}
