/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IncidentIdResolveBody struct {
	// 解決人
	ResolvedBy string `json:"resolved_by,omitempty"`
	// 解決方案描述
	Resolution string `json:"resolution,omitempty"`
	// 根本原因
	RootCause string `json:"root_cause,omitempty"`
}
