/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TrendDataDataPoints struct {

	Timestamp time.Time `json:"timestamp,omitempty"`

	Alerts int32 `json:"alerts,omitempty"`

	Incidents int32 `json:"incidents,omitempty"`

	ResourcesHealthy int32 `json:"resources_healthy,omitempty"`

	ResourcesUnhealthy int32 `json:"resources_unhealthy,omitempty"`
}
