/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SystemSettingsGeneral struct {

	SiteName string `json:"site_name,omitempty"`

	SiteUrl string `json:"site_url,omitempty"`

	TimeZone string `json:"time_zone,omitempty"`

	Language string `json:"language,omitempty"`
}
