/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 管道特定的配置
type NotificationChannelConfiguration struct {

	SmtpHost string `json:"smtp_host,omitempty"`

	SmtpPort int32 `json:"smtp_port,omitempty"`

	SmtpUsername string `json:"smtp_username,omitempty"`

	SmtpFrom string `json:"smtp_from,omitempty"`

	Url string `json:"url,omitempty"`

	Method string `json:"method,omitempty"`

	Headers *interface{} `json:"headers,omitempty"`

	WebhookUrl string `json:"webhook_url,omitempty"`

	Channel string `json:"channel,omitempty"`

	Mention string `json:"mention,omitempty"`

	AccessToken string `json:"access_token,omitempty"`

	ApiEndpoint string `json:"api_endpoint,omitempty"`

	ApiKey string `json:"api_key,omitempty"`

	SenderId string `json:"sender_id,omitempty"`
}
