/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AlertRuleCondition struct {

	Metric string `json:"metric,omitempty"`

	Operator string `json:"operator,omitempty"`

	Threshold float64 `json:"threshold,omitempty"`
	// 持續時間（秒）
	Duration int32 `json:"duration,omitempty"`
}
