/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiagnosticTaskResponse struct {

	SessionId string `json:"session_id,omitempty"`

	Status string `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
	// 預估完成時間（秒）
	EstimatedTime int32 `json:"estimated_time,omitempty"`
}
