/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Pagination struct {
	// 當前頁碼
	Page int32 `json:"page,omitempty"`
	// 每頁筆數
	PageSize int32 `json:"page_size,omitempty"`
	// 總筆數
	Total int32 `json:"total,omitempty"`
	// 總頁數
	TotalPages int32 `json:"total_pages,omitempty"`
}
