/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AiGeneratedReport struct {

	ReportType string `json:"report_type,omitempty"`
	// AI 生成的報告內容（Markdown 格式）
	Content string `json:"content,omitempty"`

	KeyFindings []string `json:"key_findings,omitempty"`

	Recommendations []string `json:"recommendations,omitempty"`

	ConfidenceScore float32 `json:"confidence_score,omitempty"`

	GeneratedAt time.Time `json:"generated_at,omitempty"`
}
