/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DashboardSummaryKpis struct {
	// 系統可用性百分比
	Availability float32 `json:"availability,omitempty"`
	// 平均修復時間（分鐘）
	Mttr float64 `json:"mttr,omitempty"`
	// 事件發生率
	IncidentRate float64 `json:"incident_rate,omitempty"`
}
