/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	Alerts []InlineResponse2001Alerts `json:"alerts,omitempty"`

	Total int32 `json:"total,omitempty"`

	FiringCount int32 `json:"firing_count,omitempty"`

	ResolvedCount int32 `json:"resolved_count,omitempty"`
}
