/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MaintenanceWindow struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	StartTime time.Time `json:"start_time,omitempty"`

	EndTime time.Time `json:"end_time,omitempty"`

	Recurring bool `json:"recurring,omitempty"`

	RecurrencePattern string `json:"recurrence_pattern,omitempty"`

	AffectedResources []string `json:"affected_resources,omitempty"`

	CreatedBy string `json:"created_by,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
