/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type NotificationChannel struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Type_ string `json:"type"`

	Enabled bool `json:"enabled"`

	Configuration *NotificationChannelConfiguration `json:"configuration,omitempty"`

	TestStatus *NotificationChannelTestStatus `json:"test_status,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
