/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScriptUpdateRequest struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Content string `json:"content,omitempty"`

	Parameters []interface{} `json:"parameters,omitempty"`

	Tags []string `json:"tags,omitempty"`
}
