/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type User struct {

	Id string `json:"id"`

	Username string `json:"username"`

	Email string `json:"email"`

	Name string `json:"name,omitempty"`

	Role string `json:"role"`

	Teams []UserTeams `json:"teams,omitempty"`

	Department string `json:"department,omitempty"`

	Phone string `json:"phone,omitempty"`

	AvatarUrl string `json:"avatar_url,omitempty"`

	LastLogin time.Time `json:"last_login,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
