/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Team struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	ManagerId string `json:"manager_id,omitempty"`

	ManagerName string `json:"manager_name,omitempty"`

	MemberCount int32 `json:"member_count,omitempty"`

	Members []TeamMembers `json:"members,omitempty"`

	NotificationSettings *TeamNotificationSettings `json:"notification_settings,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
