/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScriptParameters struct {

	Name string `json:"name,omitempty"`

	Type_ string `json:"type,omitempty"`

	Required bool `json:"required,omitempty"`
	// 參數的預設值（可以是任何類型）
	Default_ *OneOfScriptParametersDefault_ `json:"default,omitempty"`

	Description string `json:"description,omitempty"`
}
