/*
 * SRE Platform - Control Plane API
 *
 * The Control Plane is the central management hub for the SRE Platform. It provides the Web UI and APIs for managing resources, users, incidents, and more. It orchestrates diagnostic tasks by calling the SRE Assistant service. 
 *
 * API version: 1.0.0
 * Contact: sre-platform@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Execution struct {

	Id string `json:"id,omitempty"`

	ScriptId string `json:"script_id,omitempty"`

	ScriptName string `json:"script_name,omitempty"`

	Status string `json:"status,omitempty"`

	Parameters *interface{} `json:"parameters,omitempty"`

	TargetResources []string `json:"target_resources,omitempty"`

	Output string `json:"output,omitempty"`

	Error_ string `json:"error,omitempty"`

	StartedAt time.Time `json:"started_at,omitempty"`

	CompletedAt time.Time `json:"completed_at,omitempty"`

	ExecutedBy string `json:"executed_by,omitempty"`
}
