# SRE Platform SRE Assistant API Specification
# Version: 1.0.0
# Description: API specification for the SRE Platform SRE Assistant service.

openapi: 3.0.3
info:
  title: SRE Platform - SRE Assistant API
  description: |
    The SRE Assistant is a headless AI-powered diagnostic engine for the SRE Platform. It receives tasks from the Control Plane, performs complex analysis, and returns structured results.
  version: 1.0.0
  contact:
    name: SRE Platform Team
    email: sre-platform@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: http://localhost:8000
    description: SRE Assistant Development Server
  - url: https://sre-assistant.sre-platform.example.com
    description: Production Server (SRE Assistant)

tags:
  - name: Core
    description: 核心系統功能
  - name: Diagnostics
    description: 診斷分析
  - name: Workflows
    description: 工作流管理
  - name: Tools
    description: 工具狀態

paths:
  # ============================================
  # Core - 核心系統功能
  # ============================================
  /api/v1/healthz:
    get:
      tags: [Core]
      summary: 服務健康檢查
      description: 檢查服務是否存活
      operationId: sa_checkHealth
      responses:
        "200":
          description: 服務健康
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"

  /api/v1/readyz:
    get:
      tags: [Core]
      summary: 服務就緒檢查
      description: 檢查服務及其依賴是否就緒
      operationId: sa_checkReadiness
      responses:
        "200":
          description: 服務就緒
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadinessStatus"
        "503":
          description: 服務未就緒

  /api/v1/metrics:
    get:
      tags: [Core]
      summary: Prometheus 指標
      description: 獲取 Prometheus 格式的系統指標
      operationId: sa_getMetrics
      responses:
        "200":
          description: Prometheus 指標
          content:
            text/plain:
              schema:
                type: string

  # ============================================
  # Diagnostics - 診斷分析
  # ============================================
  /api/v1/diagnostics/deployment:
    post:
      tags: [Diagnostics]
      summary: 部署診斷
      description: 分析部署問題並提供診斷報告
      operationId: diagnoseDeployment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DiagnosticRequest"
      responses:
        "202":
          description: 診斷任務已接受
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiagnosticTaskResponse"

  /api/v1/diagnostics/alerts:
    post:
      tags: [Diagnostics]
      summary: 告警分析
      description: 分析告警並提供根因分析
      operationId: analyzeAlerts
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlertAnalysisRequest"
      responses:
        "202":
          description: 分析任務已接受
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiagnosticTaskResponse"

  /api/v1/diagnostics/capacity:
    post:
      tags: [Diagnostics]
      summary: 容量分析
      description: 分析資源使用趨勢並預測容量需求
      operationId: analyzeCapacity
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CapacityAnalysisRequest"
      responses:
        "200":
          description: 容量分析結果
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CapacityAnalysisResponse"

  /api/v1/diagnostics/{sessionId}/status:
    get:
      tags: [Diagnostics]
      summary: 查詢診斷狀態
      description: 查詢非同步診斷任務的狀態
      operationId: getDiagnosticStatus
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 診斷狀態
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiagnosticStatus"

  /api/v1/diagnostics/history:
    get:
      tags: [Diagnostics]
      summary: 診斷歷史
      description: 查詢歷史診斷記錄
      operationId: getDiagnosticHistory
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PageSizeParam"
        - name: start_time
          in: query
          schema:
            type: string
            format: date-time
        - name: end_time
          in: query
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: 診斷歷史列表
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiagnosticHistoryList"

  /api/v1/execute:
    post:
      tags: [Diagnostics]
      summary: 自然語言查詢
      description: 接受自然語言查詢，AI 自動解析並執行相應操作
      operationId: executeNaturalLanguageQuery
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                context:
                  type: object
                options:
                  type: object
      responses:
        "200":
          description: 查詢成功
        "202":
          description: 長時間查詢任務已接受

  # ============================================
  # Workflows & Tools
  # ============================================
  /api/v1/workflows/templates:
    get:
      tags: [Workflows]
      summary: 獲取工作流模板
      operationId: listWorkflowTemplates
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of workflow templates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /api/v1/tools/status:
    get:
      tags: [Tools]
      summary: 獲取工具狀態
      operationId: getToolsStatus
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of available tools and their status
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object


# ============================================
# Components
# ============================================
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Keycloak M2M JWT Token

  parameters:
    PageParam:
      name: page
      in: query
      description: 頁碼（從 1 開始）
      schema:
        type: integer
        minimum: 1
        default: 1

    PageSizeParam:
      name: page_size
      in: query
      description: 每頁筆數
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  responses:
    BadRequest:
      description: 請求參數錯誤
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Unauthorized:
      description: 未授權
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Forbidden:
      description: 無權限
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFound:
      description: 資源不存在
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalServerError:
      description: 內部伺服器錯誤
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    # ============================================
    # Common Schemas
    # ============================================
    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: 錯誤代碼
        message:
          type: string
          description: 錯誤訊息
        details:
          type: object
          description: 錯誤詳情
        request_id:
          type: string
          description: 請求追蹤 ID

    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: 當前頁碼
        page_size:
          type: integer
          description: 每頁筆數
        total:
          type: integer
          description: 總筆數
        total_pages:
          type: integer
          description: 總頁數

    # ============================================
    # Core Schemas
    # ============================================
    HealthStatus:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
        timestamp:
          type: string
          format: date-time
        version:
          type: string
        uptime:
          type: integer
          description: 運行時間（秒）

    ReadinessStatus:
      type: object
      required:
        - ready
        - checks
      properties:
        ready:
          type: boolean
        checks:
          type: object
          properties:
            prometheus:
              type: boolean
            loki:
              type: boolean
            control_plane:
              type: boolean

    # ============================================
    # Diagnostic Schemas
    # ============================================
    DiagnosticRequest:
      type: object
      required:
        - incident_id
        - severity
        - affected_services
      properties:
        incident_id:
          type: string
        severity:
          type: string
          enum: [P0, P1, P2, P3]
        affected_services:
          type: array
          items:
            type: string
        context:
          type: object
          additionalProperties: true

    DiagnosticTaskResponse:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [accepted, processing, completed, failed]
        message:
          type: string
        estimated_time:
          type: integer
          description: 預估完成時間（秒）

    DiagnosticStatus:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [processing, completed, failed]
        progress:
          type: integer
          minimum: 0
          maximum: 100
        current_step:
          type: string
        result:
          $ref: "#/components/schemas/DiagnosticResult"
        error:
          type: string

    DiagnosticResult:
      type: object
      properties:
        summary:
          type: string
        findings:
          type: array
          items:
            type: object
            properties:
              source:
                type: string
              severity:
                type: string
                enum: [critical, warning, info]
              message:
                type: string
              evidence:
                type: object
              timestamp:
                type: string
                format: date-time
        recommended_actions:
          type: array
          items:
            type: string
        confidence_score:
          type: number
          format: float
          minimum: 0
          maximum: 1
        tools_used:
          type: array
          items:
            type: string
        execution_time:
          type: number
          description: 執行時間（秒）

    DiagnosticHistoryList:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              session_id:
                type: string
              incident_id:
                type: string
              status:
                type: string
              created_at:
                type: string
                format: date-time
              completed_at:
                type: string
                format: date-time
              summary:
                type: string
        pagination:
          $ref: "#/components/schemas/Pagination"

    AlertAnalysisRequest:
      type: object
      required:
        - alert_ids
      properties:
        alert_ids:
          type: array
          items:
            type: string
        correlation_window:
          type: integer
          default: 300
          description: 關聯時間窗口（秒）

    CapacityAnalysisRequest:
      type: object
      required:
        - resource_ids
        - metric_type
      properties:
        resource_ids:
          type: array
          items:
            type: string
        metric_type:
          type: string
          enum: [cpu, memory, disk, network]
        forecast_days:
          type: integer
          default: 30
          minimum: 7
          maximum: 365

    CapacityAnalysisResponse:
      type: object
      properties:
        current_usage:
          type: object
          properties:
            average:
              type: number
            peak:
              type: number
            percentile_95:
              type: number
        forecast:
          type: object
          properties:
            trend:
              type: string
              enum: [increasing, stable, decreasing]
            days_to_capacity:
              type: integer
              description: 預測多少天後達到容量上限
            growth_rate:
              type: number
              description: 月增長率百分比
            capacity_alerts:
              type: array
              items:
                type: object
                properties:
                  alert_type:
                    type: string
                  threshold:
                    type: string
                  estimated_date:
                    type: string
                    format: date-time
                  days_remaining:
                    type: integer
                  severity:
                    type: string
        recommendations:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum: [scale_up, scale_down, optimize]
              resource:
                type: string
              priority:
                type: string
                enum: [immediate, high, medium, low]
              current_allocation:
                type: number
              recommended_allocation:
                type: number
              reasoning:
                type: string
              cost_impact:
                type: object
                properties:
                  monthly_increase:
                    type: number
                  currency:
                    type: string
                    default: USD
        chart_data:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              historical:
                type: number
              predicted:
                type: number
