# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AlertAnalysisRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, alert_ids: List[str]=None, correlation_window: int=300):  # noqa: E501
        """AlertAnalysisRequest - a model defined in Swagger

        :param alert_ids: The alert_ids of this AlertAnalysisRequest.  # noqa: E501
        :type alert_ids: List[str]
        :param correlation_window: The correlation_window of this AlertAnalysisRequest.  # noqa: E501
        :type correlation_window: int
        """
        self.swagger_types = {
            'alert_ids': List[str],
            'correlation_window': int
        }

        self.attribute_map = {
            'alert_ids': 'alert_ids',
            'correlation_window': 'correlation_window'
        }
        self._alert_ids = alert_ids
        self._correlation_window = correlation_window

    @classmethod
    def from_dict(cls, dikt) -> 'AlertAnalysisRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertAnalysisRequest of this AlertAnalysisRequest.  # noqa: E501
        :rtype: AlertAnalysisRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alert_ids(self) -> List[str]:
        """Gets the alert_ids of this AlertAnalysisRequest.


        :return: The alert_ids of this AlertAnalysisRequest.
        :rtype: List[str]
        """
        return self._alert_ids

    @alert_ids.setter
    def alert_ids(self, alert_ids: List[str]):
        """Sets the alert_ids of this AlertAnalysisRequest.


        :param alert_ids: The alert_ids of this AlertAnalysisRequest.
        :type alert_ids: List[str]
        """
        if alert_ids is None:
            raise ValueError("Invalid value for `alert_ids`, must not be `None`")  # noqa: E501

        self._alert_ids = alert_ids

    @property
    def correlation_window(self) -> int:
        """Gets the correlation_window of this AlertAnalysisRequest.

        關聯時間窗口（秒）  # noqa: E501

        :return: The correlation_window of this AlertAnalysisRequest.
        :rtype: int
        """
        return self._correlation_window

    @correlation_window.setter
    def correlation_window(self, correlation_window: int):
        """Sets the correlation_window of this AlertAnalysisRequest.

        關聯時間窗口（秒）  # noqa: E501

        :param correlation_window: The correlation_window of this AlertAnalysisRequest.
        :type correlation_window: int
        """

        self._correlation_window = correlation_window
