# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CapacityAnalysisResponseChartData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, historical: float=None, predicted: float=None):  # noqa: E501
        """CapacityAnalysisResponseChartData - a model defined in Swagger

        :param _date: The _date of this CapacityAnalysisResponseChartData.  # noqa: E501
        :type _date: date
        :param historical: The historical of this CapacityAnalysisResponseChartData.  # noqa: E501
        :type historical: float
        :param predicted: The predicted of this CapacityAnalysisResponseChartData.  # noqa: E501
        :type predicted: float
        """
        self.swagger_types = {
            '_date': date,
            'historical': float,
            'predicted': float
        }

        self.attribute_map = {
            '_date': 'date',
            'historical': 'historical',
            'predicted': 'predicted'
        }
        self.__date = _date
        self._historical = historical
        self._predicted = predicted

    @classmethod
    def from_dict(cls, dikt) -> 'CapacityAnalysisResponseChartData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CapacityAnalysisResponse_chart_data of this CapacityAnalysisResponseChartData.  # noqa: E501
        :rtype: CapacityAnalysisResponseChartData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this CapacityAnalysisResponseChartData.


        :return: The _date of this CapacityAnalysisResponseChartData.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this CapacityAnalysisResponseChartData.


        :param _date: The _date of this CapacityAnalysisResponseChartData.
        :type _date: date
        """

        self.__date = _date

    @property
    def historical(self) -> float:
        """Gets the historical of this CapacityAnalysisResponseChartData.


        :return: The historical of this CapacityAnalysisResponseChartData.
        :rtype: float
        """
        return self._historical

    @historical.setter
    def historical(self, historical: float):
        """Sets the historical of this CapacityAnalysisResponseChartData.


        :param historical: The historical of this CapacityAnalysisResponseChartData.
        :type historical: float
        """

        self._historical = historical

    @property
    def predicted(self) -> float:
        """Gets the predicted of this CapacityAnalysisResponseChartData.


        :return: The predicted of this CapacityAnalysisResponseChartData.
        :rtype: float
        """
        return self._predicted

    @predicted.setter
    def predicted(self, predicted: float):
        """Sets the predicted of this CapacityAnalysisResponseChartData.


        :param predicted: The predicted of this CapacityAnalysisResponseChartData.
        :type predicted: float
        """

        self._predicted = predicted
