# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DiagnosticHistoryListItems(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, incident_id: str=None, status: str=None, created_at: datetime=None, completed_at: datetime=None, summary: str=None):  # noqa: E501
        """DiagnosticHistoryListItems - a model defined in Swagger

        :param session_id: The session_id of this DiagnosticHistoryListItems.  # noqa: E501
        :type session_id: str
        :param incident_id: The incident_id of this DiagnosticHistoryListItems.  # noqa: E501
        :type incident_id: str
        :param status: The status of this DiagnosticHistoryListItems.  # noqa: E501
        :type status: str
        :param created_at: The created_at of this DiagnosticHistoryListItems.  # noqa: E501
        :type created_at: datetime
        :param completed_at: The completed_at of this DiagnosticHistoryListItems.  # noqa: E501
        :type completed_at: datetime
        :param summary: The summary of this DiagnosticHistoryListItems.  # noqa: E501
        :type summary: str
        """
        self.swagger_types = {
            'session_id': str,
            'incident_id': str,
            'status': str,
            'created_at': datetime,
            'completed_at': datetime,
            'summary': str
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'incident_id': 'incident_id',
            'status': 'status',
            'created_at': 'created_at',
            'completed_at': 'completed_at',
            'summary': 'summary'
        }
        self._session_id = session_id
        self._incident_id = incident_id
        self._status = status
        self._created_at = created_at
        self._completed_at = completed_at
        self._summary = summary

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnosticHistoryListItems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnosticHistoryList_items of this DiagnosticHistoryListItems.  # noqa: E501
        :rtype: DiagnosticHistoryListItems
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this DiagnosticHistoryListItems.


        :return: The session_id of this DiagnosticHistoryListItems.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this DiagnosticHistoryListItems.


        :param session_id: The session_id of this DiagnosticHistoryListItems.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def incident_id(self) -> str:
        """Gets the incident_id of this DiagnosticHistoryListItems.


        :return: The incident_id of this DiagnosticHistoryListItems.
        :rtype: str
        """
        return self._incident_id

    @incident_id.setter
    def incident_id(self, incident_id: str):
        """Sets the incident_id of this DiagnosticHistoryListItems.


        :param incident_id: The incident_id of this DiagnosticHistoryListItems.
        :type incident_id: str
        """

        self._incident_id = incident_id

    @property
    def status(self) -> str:
        """Gets the status of this DiagnosticHistoryListItems.


        :return: The status of this DiagnosticHistoryListItems.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this DiagnosticHistoryListItems.


        :param status: The status of this DiagnosticHistoryListItems.
        :type status: str
        """

        self._status = status

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this DiagnosticHistoryListItems.


        :return: The created_at of this DiagnosticHistoryListItems.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this DiagnosticHistoryListItems.


        :param created_at: The created_at of this DiagnosticHistoryListItems.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def completed_at(self) -> datetime:
        """Gets the completed_at of this DiagnosticHistoryListItems.


        :return: The completed_at of this DiagnosticHistoryListItems.
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at: datetime):
        """Sets the completed_at of this DiagnosticHistoryListItems.


        :param completed_at: The completed_at of this DiagnosticHistoryListItems.
        :type completed_at: datetime
        """

        self._completed_at = completed_at

    @property
    def summary(self) -> str:
        """Gets the summary of this DiagnosticHistoryListItems.


        :return: The summary of this DiagnosticHistoryListItems.
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary: str):
        """Sets the summary of this DiagnosticHistoryListItems.


        :param summary: The summary of this DiagnosticHistoryListItems.
        :type summary: str
        """

        self._summary = summary
