# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.diagnostic_history_list_items import DiagnosticHistoryListItems  # noqa: F401,E501
from swagger_server.models.pagination import Pagination  # noqa: F401,E501
from swagger_server import util


class DiagnosticHistoryList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[DiagnosticHistoryListItems]=None, pagination: Pagination=None):  # noqa: E501
        """DiagnosticHistoryList - a model defined in Swagger

        :param items: The items of this DiagnosticHistoryList.  # noqa: E501
        :type items: List[DiagnosticHistoryListItems]
        :param pagination: The pagination of this DiagnosticHistoryList.  # noqa: E501
        :type pagination: Pagination
        """
        self.swagger_types = {
            'items': List[DiagnosticHistoryListItems],
            'pagination': Pagination
        }

        self.attribute_map = {
            'items': 'items',
            'pagination': 'pagination'
        }
        self._items = items
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnosticHistoryList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnosticHistoryList of this DiagnosticHistoryList.  # noqa: E501
        :rtype: DiagnosticHistoryList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[DiagnosticHistoryListItems]:
        """Gets the items of this DiagnosticHistoryList.


        :return: The items of this DiagnosticHistoryList.
        :rtype: List[DiagnosticHistoryListItems]
        """
        return self._items

    @items.setter
    def items(self, items: List[DiagnosticHistoryListItems]):
        """Sets the items of this DiagnosticHistoryList.


        :param items: The items of this DiagnosticHistoryList.
        :type items: List[DiagnosticHistoryListItems]
        """

        self._items = items

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this DiagnosticHistoryList.


        :return: The pagination of this DiagnosticHistoryList.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this DiagnosticHistoryList.


        :param pagination: The pagination of this DiagnosticHistoryList.
        :type pagination: Pagination
        """

        self._pagination = pagination
