# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DiagnosticTaskResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, session_id: str=None, status: str=None, message: str=None, estimated_time: int=None):  # noqa: E501
        """DiagnosticTaskResponse - a model defined in Swagger

        :param session_id: The session_id of this DiagnosticTaskResponse.  # noqa: E501
        :type session_id: str
        :param status: The status of this DiagnosticTaskResponse.  # noqa: E501
        :type status: str
        :param message: The message of this DiagnosticTaskResponse.  # noqa: E501
        :type message: str
        :param estimated_time: The estimated_time of this DiagnosticTaskResponse.  # noqa: E501
        :type estimated_time: int
        """
        self.swagger_types = {
            'session_id': str,
            'status': str,
            'message': str,
            'estimated_time': int
        }

        self.attribute_map = {
            'session_id': 'session_id',
            'status': 'status',
            'message': 'message',
            'estimated_time': 'estimated_time'
        }
        self._session_id = session_id
        self._status = status
        self._message = message
        self._estimated_time = estimated_time

    @classmethod
    def from_dict(cls, dikt) -> 'DiagnosticTaskResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DiagnosticTaskResponse of this DiagnosticTaskResponse.  # noqa: E501
        :rtype: DiagnosticTaskResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def session_id(self) -> str:
        """Gets the session_id of this DiagnosticTaskResponse.


        :return: The session_id of this DiagnosticTaskResponse.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this DiagnosticTaskResponse.


        :param session_id: The session_id of this DiagnosticTaskResponse.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def status(self) -> str:
        """Gets the status of this DiagnosticTaskResponse.


        :return: The status of this DiagnosticTaskResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this DiagnosticTaskResponse.


        :param status: The status of this DiagnosticTaskResponse.
        :type status: str
        """
        allowed_values = ["accepted", "processing", "completed", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this DiagnosticTaskResponse.


        :return: The message of this DiagnosticTaskResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this DiagnosticTaskResponse.


        :param message: The message of this DiagnosticTaskResponse.
        :type message: str
        """

        self._message = message

    @property
    def estimated_time(self) -> int:
        """Gets the estimated_time of this DiagnosticTaskResponse.

        預估完成時間（秒）  # noqa: E501

        :return: The estimated_time of this DiagnosticTaskResponse.
        :rtype: int
        """
        return self._estimated_time

    @estimated_time.setter
    def estimated_time(self, estimated_time: int):
        """Sets the estimated_time of this DiagnosticTaskResponse.

        預估完成時間（秒）  # noqa: E501

        :param estimated_time: The estimated_time of this DiagnosticTaskResponse.
        :type estimated_time: int
        """

        self._estimated_time = estimated_time
