# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Pagination(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, page: int=None, page_size: int=None, total: int=None, total_pages: int=None):  # noqa: E501
        """Pagination - a model defined in Swagger

        :param page: The page of this Pagination.  # noqa: E501
        :type page: int
        :param page_size: The page_size of this Pagination.  # noqa: E501
        :type page_size: int
        :param total: The total of this Pagination.  # noqa: E501
        :type total: int
        :param total_pages: The total_pages of this Pagination.  # noqa: E501
        :type total_pages: int
        """
        self.swagger_types = {
            'page': int,
            'page_size': int,
            'total': int,
            'total_pages': int
        }

        self.attribute_map = {
            'page': 'page',
            'page_size': 'page_size',
            'total': 'total',
            'total_pages': 'total_pages'
        }
        self._page = page
        self._page_size = page_size
        self._total = total
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this Pagination.

        當前頁碼  # noqa: E501

        :return: The page of this Pagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this Pagination.

        當前頁碼  # noqa: E501

        :param page: The page of this Pagination.
        :type page: int
        """

        self._page = page

    @property
    def page_size(self) -> int:
        """Gets the page_size of this Pagination.

        每頁筆數  # noqa: E501

        :return: The page_size of this Pagination.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this Pagination.

        每頁筆數  # noqa: E501

        :param page_size: The page_size of this Pagination.
        :type page_size: int
        """

        self._page_size = page_size

    @property
    def total(self) -> int:
        """Gets the total of this Pagination.

        總筆數  # noqa: E501

        :return: The total of this Pagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this Pagination.

        總筆數  # noqa: E501

        :param total: The total of this Pagination.
        :type total: int
        """

        self._total = total

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this Pagination.

        總頁數  # noqa: E501

        :return: The total_pages of this Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this Pagination.

        總頁數  # noqa: E501

        :param total_pages: The total_pages of this Pagination.
        :type total_pages: int
        """

        self._total_pages = total_pages
