# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReadinessStatusChecks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, prometheus: bool=None, loki: bool=None, control_plane: bool=None):  # noqa: E501
        """ReadinessStatusChecks - a model defined in Swagger

        :param prometheus: The prometheus of this ReadinessStatusChecks.  # noqa: E501
        :type prometheus: bool
        :param loki: The loki of this ReadinessStatusChecks.  # noqa: E501
        :type loki: bool
        :param control_plane: The control_plane of this ReadinessStatusChecks.  # noqa: E501
        :type control_plane: bool
        """
        self.swagger_types = {
            'prometheus': bool,
            'loki': bool,
            'control_plane': bool
        }

        self.attribute_map = {
            'prometheus': 'prometheus',
            'loki': 'loki',
            'control_plane': 'control_plane'
        }
        self._prometheus = prometheus
        self._loki = loki
        self._control_plane = control_plane

    @classmethod
    def from_dict(cls, dikt) -> 'ReadinessStatusChecks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReadinessStatus_checks of this ReadinessStatusChecks.  # noqa: E501
        :rtype: ReadinessStatusChecks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prometheus(self) -> bool:
        """Gets the prometheus of this ReadinessStatusChecks.


        :return: The prometheus of this ReadinessStatusChecks.
        :rtype: bool
        """
        return self._prometheus

    @prometheus.setter
    def prometheus(self, prometheus: bool):
        """Sets the prometheus of this ReadinessStatusChecks.


        :param prometheus: The prometheus of this ReadinessStatusChecks.
        :type prometheus: bool
        """

        self._prometheus = prometheus

    @property
    def loki(self) -> bool:
        """Gets the loki of this ReadinessStatusChecks.


        :return: The loki of this ReadinessStatusChecks.
        :rtype: bool
        """
        return self._loki

    @loki.setter
    def loki(self, loki: bool):
        """Sets the loki of this ReadinessStatusChecks.


        :param loki: The loki of this ReadinessStatusChecks.
        :type loki: bool
        """

        self._loki = loki

    @property
    def control_plane(self) -> bool:
        """Gets the control_plane of this ReadinessStatusChecks.


        :return: The control_plane of this ReadinessStatusChecks.
        :rtype: bool
        """
        return self._control_plane

    @control_plane.setter
    def control_plane(self, control_plane: bool):
        """Sets the control_plane of this ReadinessStatusChecks.


        :param control_plane: The control_plane of this ReadinessStatusChecks.
        :type control_plane: bool
        """

        self._control_plane = control_plane
