auth:
  provider: keycloak
  keycloak:
    url: ${KEYCLOAK_URL:"http://localhost:8080"}
    realm: ${KEYCLOAK_REALM:"sre-platform"}
    audience: "sre-assistant"
    allowed_client_id: "control-plane"

redis:
  url: ${REDIS_URL:"redis://127.0.0.1:6379/0"}

workflow:
  diagnosis_timeout_seconds: 120
  max_retries: 2
  retry_delay_seconds: 1

prometheus:
  base_url: "http://localhost:9090/select/0/prometheus"
