global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'self_vmagent'
    static_configs:
      - targets: ['localhost:8429']
  - job_name: 'snmp'
    static_configs:
      - targets: ['localhost:9116']
